#!/bin/bash

# This file is sourced by all i3blocks block commands in this directory
BASE_PROP=1

urgent() {
    # Tells i3bar to mark this block as urgent
    exit 33
}

full_text() {
    if [ $BASE_PROP -eq 1 ]; then
        echo "$1"
    fi

    BASE_PROP=2
}

short_text() {
    case $BASE_PROP in
        1)
            echo "$1"
            echo "$1"
            ;;
        2)
            echo "$1"
            ;;
        3)
            ;;
    esac

    BASE_PROP=3
}

color() {
    case $BASE_PROP in
        1)
            echo ""
            echo ""
            echo "#$1"
            ;;
        2)
            echo ""
            echo "#$1"
            ;;
        3)
            echo "#$1"
            ;;
    esac

    BASE_PROP=4
}
