#!/bin/bash

# Fetches 'full_text', 'short_text', 'color' and 'urgent'
source ~/scripts/i3/base

case $BLOCK_BUTTON in
    1) true ;;
    2) true ;;
    3) true ;;
    4) true ;;
    5) true ;;
esac

icon_discharging=🔋
icon_charging=🔌
icon_full=⚡

status=$(acpi | sed -e 's/battery /B/i' \
                    -e 's/:\( ...\).[a-zA-Z]*, /\1/' \
                    -e 's/%.*/%/' \
                    -e '$! s/$/ | /' \
                    -e s/Unk/$icon_full/ \
                    -e s/Cha/$icon_charging/ \
                    -e s/Dis/$icon_discharging/ \
                    -e s/Ful/$icon_full/ \
                    | head -n 4 | tr -d '\n')

full_text "$status"
short_text "$status"

#short_text 'short here'

# Note: auto-prepends '#'
color 'FFFFFF'

# Uncomment to exit with urgent status
#urgent
