#!/bin/bash

# Fetches 'full_text', 'short_text', 'color' and 'urgent'
source ~/scripts/i3/base

# Config
pasink=0

case $BLOCK_BUTTON in
    1) ~/scripts/util/volume-ctrl.sh mute ;; # mouse left
    2) ~/scripts/util/volume-ctrl.sh mute ;; # mouse middle
    3) ~/scripts/util/volume-ctrl.sh mute ;; # mouse right
    4) ~/scripts/util/volume-ctrl.sh up ;; # mouse scroll up
    5) ~/scripts/util/volume-ctrl.sh down ;; # mouse scroll down
esac

icon_volume=🔊
icon_muted=🔇

pasink2=$(( $pasink + 1 ))
status=$(pactl list sinks | sed -n "/^Sink #$pasink/,/^Sink #$pasink2/{/Sink #$pasink2/!p}")

volume=$(echo "$status" | grep '^\s\+Volume:' | sed 's/%//g' | awk '{print int(($5+$12)/2) "%"}')
muted=$(echo "$status" | grep '^\s\+Mute:' | awk '{print $2}')

if [ "$muted" = 'yes' ]; then
    full_text "${icon_muted}muted"
    short_text "${icon_muted}"
else
    full_text "$icon_volume$volume"
fi

# Note: auto-prepends '#'
color 'FFFFFF'

# Uncomment to exit with urgent status
#urgent
