#!/bin/bash

# Fetches 'full_text', 'short_text', 'color' and 'urgent'
source ~/scripts/i3/base

case $BLOCK_BUTTON in
    1) true ;;
    2) true ;;
    3) true ;;
    4) true ;;
    5) true ;;
esac

icon_wifi=📶
icon_nowifi=⛔

if [ "$(cat /sys/class/net/w*/operstate)" = 'up' ]; then
    quality=$(</proc/net/wireless awk '/^\s*w/{print int($3 * 100 / 70) "%"}')
    ssid=$(nmcli device | awk '/wifi/{print $4}' | sed 1q)
    wdev=$(nmcli device | awk '/wifi/{print $1}' | sed 1q)
    ip=$(ip addr | sed -n "/$wdev/,/^[0-9]\+:/p" | awk '/inet /{print $2}' | cut -d/ -f1)

    full_text "$icon_wifi$quality $ssid ($ip)"

    short_text "$icon_wifi$quality ($ip)"
else
    full_text "$icon_wifi$icon_nowifi"
fi

# Note: auto-prepends '#'
color 'FFFFFF'

# Uncomment to exit with urgent status
#urgent
